// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzqqu6seIe-6agptquDtokpEk5E5AyKM',
    appId: '1:163277294153:web:9182fbe9458b05c1214d98',
    messagingSenderId: '163277294153',
    projectId: 'harvest-hub-d7d24',
    authDomain: 'harvest-hub-d7d24.firebaseapp.com',
    storageBucket: 'harvest-hub-d7d24.firebasestorage.app',
    measurementId: 'G-P13GQR5B5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fB2yOAJK2romS9xGCPrNiDIgwKtstmc',
    appId: '1:163277294153:android:e833257db2892762214d98',
    messagingSenderId: '163277294153',
    projectId: 'harvest-hub-d7d24',
    storageBucket: 'harvest-hub-d7d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWU9-kBXYA_aZBKrePD2f2CfzTuz58l1A',
    appId: '1:163277294153:ios:21d098a81b35ce3b214d98',
    messagingSenderId: '163277294153',
    projectId: 'harvest-hub-d7d24',
    storageBucket: 'harvest-hub-d7d24.firebasestorage.app',
    androidClientId: '163277294153-d9b23ssfqfphe9j2q5mh7ob6tor93fov.apps.googleusercontent.com',
    iosClientId: '163277294153-hamk1u7vahvhianpv559e0ivo3p3t72m.apps.googleusercontent.com',
    iosBundleId: 'com.example.harvesthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMzqqu6seIe-6agptquDtokpEk5E5AyKM',
    appId: '1:163277294153:web:ee1a0e606f8cb60f214d98',
    messagingSenderId: '163277294153',
    projectId: 'harvest-hub-d7d24',
    authDomain: 'harvest-hub-d7d24.firebaseapp.com',
    storageBucket: 'harvest-hub-d7d24.firebasestorage.app',
    measurementId: 'G-BVHWPR9WCP',
  );
}
